name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
    - uses: actions/checkout@v2

    - name: Auto Minify
      uses: nizarmah/auto-minify@master
      with:
        directory: './'

    # Auto commits minified files to the repository
    # Ignore it if you don't want to commit the files to the repository 
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        repository: './'
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
